import { createFileRoute, Link } from "@tanstack/react-router";
import { SyncIcon } from "@/components/synkron/SyncIcon";

export const Route = createFileRoute("/terms")({ component: TermsPage });

function TermsPage() {
  return (
    <div className="bg-[#04040A] text-[#F1F5F9] min-h-screen">
      {/* Navbar */}
      <header className="fixed top-0 left-0 right-0 z-50 border-b border-white/[0.06] bg-[#04040A]/80 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2 group">
            <SyncIcon className="w-5 h-5 text-teal-400" />
            <span className="font-display font-semibold text-lg text-white group-hover:text-teal-300 transition-colors">
              Synkron
            </span>
          </Link>
          <Link
            to="/"
            className="text-slate-400 hover:text-teal-400 text-sm transition-colors"
          >
            ← Back to home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 pt-32 pb-24">
        {/* Header */}
        <div className="mb-12">
          <p className="font-mono text-teal-400 text-sm uppercase tracking-widest mb-3">
            Legal
          </p>
          <h1
            className="font-display font-bold text-white"
            style={{ fontSize: "clamp(32px, 5vw, 52px)", lineHeight: 1.1, letterSpacing: "-0.02em" }}
          >
            Terms & Conditions
          </h1>
          <p className="text-slate-500 mt-4 text-sm">Last updated: June 2026</p>
        </div>

        {/* Divider */}
        <div className="h-px bg-gradient-to-r from-teal-400/20 via-white/[0.07] to-transparent mb-12" />

        {/* Body */}
        <div className="prose-legal">
          <p className="text-slate-300 leading-relaxed">
            These Terms and Conditions ("Terms") govern your access to and use
            of the Synkron website and service (the "Service"). By accessing or
            using the Service, you agree to these Terms. If you do not agree, do
            not use the Service.
          </p>

          <Section title="1. The Service">
            <p>
              Synkron is an automated documentation tool that connects to GitHub
              repositories, analyzes code changes, and proposes documentation
              updates as pull requests for your review. Synkron does not merge
              changes on your behalf. A human always decides whether to merge any
              proposed change.
            </p>
          </Section>

          <Section title="2. Eligibility and Accounts">
            <p>
              You must be at least 16 years old, or the age of majority in your
              jurisdiction, to use the Service. You are responsible for all
              activity that occurs under your account and for keeping your sign-in
              credentials secure.
            </p>
          </Section>

          <Section title="3. Your Repositories and Authorization">
            <p>
              By connecting a repository, you represent that you own it or have
              the necessary rights and permissions to grant Synkron access, to
              allow analysis of its contents, and to permit the creation of
              branches and merge requests. You are responsible for the access
              tokens you provide and for the scope of access they grant.
            </p>
          </Section>

          <Section title="4. Acceptable Use">
            <p>You agree not to:</p>
            <ul>
              <li>
                Use the Service to process content you do not have the right to
                share or modify.
              </li>
              <li>Connect repositories containing unlawful content.</li>
              <li>
                Attempt to disrupt, reverse engineer, or gain unauthorized access
                to the Service or its infrastructure.
              </li>
              <li>
                Use the Service in any way that violates GitHub's terms or any
                applicable law.
              </li>
            </ul>
          </Section>

          <Section title="5. AI-Generated Content">
            <p>
              Documentation produced by Synkron is generated by automated AI
              systems and may contain errors, omissions, or inaccuracies. All
              generated merge requests are proposals only. You are responsible
              for reviewing any generated content before merging it. We make no
              warranty that generated documentation is accurate, complete, or
              suitable for any purpose.
            </p>
          </Section>

          <Section title="6. Third-Party Services">
            <p>
              The Service integrates with third-party platforms including GitHub,
              Google Cloud, Firebase, and the Google Gemini API. Your use of
              those platforms is governed by their own terms. We are not
              responsible for the availability, accuracy, or conduct of
              third-party services.
            </p>
          </Section>

          <Section title="7. Intellectual Property">
            <p>
              The Service, including its software, design, and branding, is owned
              by Synkron and its licensors. These Terms do not grant you any
              rights to our trademarks or branding. You retain all rights to your
              code and documentation. We claim no ownership over the content you
              process through the Service.
            </p>
          </Section>

          <Section title="8. Service Availability">
            <p>
              The Service is provided on an "as is" and "as available" basis. It
              may be offered as a beta or hackathon project and may change, be
              interrupted, or be discontinued at any time without notice. We do
              not guarantee any level of uptime or availability.
            </p>
          </Section>

          <Section title="9. Disclaimer of Warranties">
            <p>
              To the fullest extent permitted by law, the Service is provided
              without warranties of any kind, whether express or implied,
              including warranties of merchantability, fitness for a particular
              purpose, and non-infringement.
            </p>
          </Section>

          <Section title="10. Limitation of Liability">
            <p>
              To the fullest extent permitted by law, Synkron and its operators
              will not be liable for any indirect, incidental, special,
              consequential, or punitive damages, or for any loss of data,
              profits, or revenue, arising from your use of the Service. Our
              total liability for any claim relating to the Service will not
              exceed the amount you paid us, if any, in the twelve months before
              the claim.
            </p>
          </Section>

          <Section title="11. Indemnification">
            <p>
              You agree to indemnify and hold harmless Synkron and its operators
              from any claims, damages, or expenses arising from your use of the
              Service, your content, or your violation of these Terms.
            </p>
          </Section>

          <Section title="12. Termination">
            <p>
              You may stop using the Service at any time by disconnecting your
              repositories and deleting your account. We may suspend or terminate
              your access if you violate these Terms or if we discontinue the
              Service.
            </p>
          </Section>

          <Section title="13. Changes to These Terms">
            <p>
              We may update these Terms from time to time. We will post the
              updated version with a new "Last updated" date. Continued use of
              the Service after changes take effect constitutes acceptance of the
              revised Terms.
            </p>
          </Section>

          <Section title="14. Governing Law">
            <p>
              These Terms are governed by the laws of the applicable jurisdiction,
              without regard to its conflict of laws rules. Any disputes will be
              subject to the courts of the applicable jurisdiction.
            </p>
          </Section>

          <Section title="15. Contact">
            <p>
              If you have questions about these Terms, contact us at{" "}
              <a
                href="mailto:contact@synkron.dev"
                className="text-teal-400 hover:text-teal-300 transition-colors"
              >
                contact@synkron.dev
              </a>
              .
            </p>
          </Section>
        </div>

        {/* Footer nav */}
        <div className="mt-16 pt-8 border-t border-white/[0.05] flex items-center justify-between">
          <Link to="/privacy" className="text-slate-500 hover:text-teal-400 text-sm transition-colors">
            ← Privacy Policy
          </Link>
          <Link to="/" className="text-slate-500 hover:text-teal-400 text-sm transition-colors">
            Back to home →
          </Link>
        </div>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 className="text-white font-display font-semibold text-xl mb-4">{title}</h2>
      <div className="text-slate-400 leading-relaxed space-y-3 [&_strong]:font-medium [&_ul]:mt-3 [&_ul]:space-y-2 [&_ul]:ml-5 [&_ul]:list-disc [&_ul]:marker:text-teal-400/60">
        {children}
      </div>
    </section>
  );
}
